# fly.toml app configuration file generated for school-pulse-api on 2024-07-28T21:34:26+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'school-pulse-api'
primary_region = 'nrt'
kill_signal = 'SIGTERM'

[build]

[mounts]
  source="school_pulse"
  destination="/priv/static/images"

[deploy]
  release_command = '/app/bin/migrate'

[env]
  PHX_HOST = 'school-pulse-api.fly.dev'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
